# 概述
----

数据分析绝对绕不过的三个包是numpy、scipy和pandas。

+ numpy是Python的数值计算扩展，专门用来处理矩阵，它的运算效率比列表更高效。
+ scipy是基于numpy的科学计算包，包括统计、线性代数等工具。
+ pandas是基于numpy的数据分析工具，能更方便的操作大型数据集。


# 基础知识
---

### List

List is a non-homogeneous data structure which stores the elements in single row and multiple rows and columns.

List can be represented by [ ]，which represents you can create an empty list like this `data = []`

List allows duplicate elements.

```python
data = [[1, 2, 3], [4, 5, 6]]
print(data[0])
print(data[1])
print(data[0][2])
# [1, 2, 3]
# [4, 5, 6]
# 3
```

### Tuple

Tuple is also a non-homogeneous data structure which stores single row and multiple rows and columns.

Tuple can be represented by  ( ) `data = ()`

Tuple allows duplicate elements.

```python
data = ((1, 2, 3), (4, 5, 6))
print(data[0])
print(data[1])
print(data[0][2])
# (1, 2, 3)
# (4, 5, 6)
# 3
```

### Tuple vs List

The primary difference between tuples and lists is that tuples are immutable as opposed to lists which are mutable. Therefore, it is possible to change the elements of a list but not a tuple.

# Why are NumPy Arrays so Fast than List
---

numpy操作数组很容易:

```python
import numpy as np

data = [1, 2, 3]
array = np.array(data)
print(array + 2)
print(array * array)
# [3 4 5]
# [1 4 9]
```

**numpy的向量化运算**和**python的循环遍历运算**效率对比，参考下面的例子可以看出差异：

- 使用python的list进行循环遍历运算测试时间

```python
import time


def pySum():
    a = list(range(10000))
    b = list(range(10000))
    c = []
    for i in range(len(a)):
        c.append(a[i]**2 + b[i]**2)
    return c

best_time = 0.0
for i in range(10):
    start_time = time.time()
    pySum()
    end_time = time.time()
    if best_time == 0:
        best_time = end_time - start_time
        continue

    if best_time > (end_time - start_time):
        best_time = end_time - start_time

print(best_time*1000)
# The best time in the 10 loop was 4.162ms
```

- 使用numpy进行向量化运算:

```python
def npSum():
    a = np.arange(10000)
    b = np.arange(10000)
    c = a**2 + b**2
    return c

# The best time in the 10 loop was 0.063ms
```

从上可以看出效率提高了两个数量级，**numpy的向量化运算**的效率要远远高于**python的循环遍历运算**。

为什么可以这么快呢?

- Numpy array is a collection of similar data-types that are densely packed in memory. A Python list can have different data-types, which puts lots of extra constraints while doing computation on it.

Numpy arrays are densely packed arrays of homogeneous type. Python lists, by contrast, are arrays of pointers to objects, even when all of them are of the same type. So, you get the benefits of locality of reference. https://stackoverflow.com/a/8385658/16317008

- Numpy is able to divide a task into multiple subtasks and process them parallelly.
- Numpy functions are implemented in C. Which again makes it faster compared to Python Lists.



# numpy
----

numpy是n维的数组对象，叫做ndarray。Python的list虽然也能表示，但是不高效 **Why?**, 看上面的原因. 

## 创建ndarray数组

#### 1) 通过list和tuple创建

```python
import numpy as np

data = [[1, 2, 3], [4, 5, 6]]
# data = ((1, 2, 3), (4, 5, 6))
# 嵌套列表会被转换为一个多维数组，它也可以被称为矩阵
array = np.array(data)
# array = np.array(((1, 2, 3), (4, 5, 6)))
# array = np.array([[1, 2, 3], [4, 5, 6]])
print(array[0])
print(array[1])
print(array[0][2])
# [1 2 3]
# [4 5 6]
# 3
```
一些输出区别：

```python
import numpy as np

data = [[1, 2, 3], [4, 5, 6]]
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print(data)
# [[1 2 3]
#  [4 5 6]]
# [[1, 2, 3], [4, 5, 6]]
```

numpy一维数组用print输出的时候为 [1 2 3 4]，没有“,”这跟python的列表是有些差异的

#### 2) 通过np.arange创建

```python
import numpy as np

arr = np.arange(5)
print(arr)
arr = np.array([np.arange(3), np.arange(3)])
print(arr)
# [0 1 2 3 4]
# [[0 1 2]
#  [0 1 2]]
```

#### 3) 基于arange以及reshape创建多维数组

```python
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)
print(arr)
# [[[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]

# [[12 13 14 15]
#  [16 17 18 19]
#  [20 21 22 23]]]
```

请注意：

- arange的长度与ndarray的维度的乘积要相等，即 24 = 2X3X4

- 几个参数就是几维数组

## ndarray的属性

Numpy数组通常是由相同种类的元素组成的, 这样有一个好处---数组元素的类型相同，能快速确定存储数据所需空间的大小. 

```python
import numpy as np

array = np.array([[1, 2, 3], [7, 8, 9]])
print(array.ndim)
# 2

print(array.shape)
# (2, 3)

print(array.itemsize)
# 8

print(array.nbytes)
# 48

print(array.dtype)
```


## ndarray数组的切片和索引

#### 1) 一维数组

一维数组的切片和索引与python的list索引类似

```python
import numpy as np

array = np.arange(6)
print(array[:4])
print(array[1:4])
print(array[:6:2])
print(array[1:6:2])
# [0 1 2 3]
# [1 2 3]
# [0 2 4]
# [1 3 5]
```

#### 2) 二维数组的切片和索引

```
import numpy as np

array = np.arange(12).reshape(3, 4)
print(array)
print(array[:2, 1:4])
print(array[:1, 1:4])
print(array[:1, 2:4])
print(array[:3, 2:4])
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

#[[1 2 3]
# [5 6 7]]

# [[1 2 3]]

# [[2 3]]

# [[ 2  3]
#  [ 6  7]
#  [10 11]]
```

## numpy常用统计函数

常用的函数如下：

**请注意函数在使用时需要指定axis轴的方向**，若不指定，默认统计整个数组。

- np.sum()，返回求和
- np.mean()，返回均值
- np.max()，返回最大值
- np.min()，返回最小值
- np.ptp()，数组沿指定轴返回最大值减去最小值，即（max-min）
- np.std()，返回标准偏差（standard deviation）
- np.var()，返回方差（variance）
- np.cumsum()，返回累加值
- np.cumprod()，返回累乘积值

```python
import numpy as np

array = np.array([[0, 1, 20, 3, 4, 5],
                  [6, 7, 8, 9, 10, 11]])

print(np.max(array))
# 沿axis=1轴方向统计
print(np.max(array, axis=1))
# 沿axis=0轴方向统计
np.max(array, axis=0)

array = np.array([6, 7, 20, 9, 10, 11])
print(np.min(array))

# 20
# [20 11]
# 6
```